version: '3.9'

services:
  db:
    image: rest-with-asp-net-udemy-db
    command: mysqld --default_authentication_plugin=caching_sha2_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_asp_net_udemy
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - erudio-network

  rest-with-asp-net-udemy:
    image: rest-with-asp-net-udemy
    build:
      context: .
      dockerfile: RestWithASPNETUdemy/Dockerfile
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MySQLConnection__MySQLConnectionString: "Server=db;Port=3308;DataBase=rest_with_asp_net_udemy;Uid=docker;Pwd=docker"
    ports:
      - 44300:80
    volumes:
      - ./dataProtectionKeys:/root/.aspnet/DataProtection-Keys
    depends_on:
      - db
    networks:
      - erudio-network
networks:
  erudio-network:
    driver: bridge